spring:
  application:
    name: agent-server
  profiles:
    active: local
  main:
    allow-circular-references: true # 允许循环依赖
  config:
    import:
      - optional:classpath:application-${spring.profiles.active}.yaml # 加载【本地】配置
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml # 加载【Nacos】的配置

server:
  port: 48089

logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log # 日志文件名
